---
- name: pre-install | Install transport Https to handle SSL layer.
  apt:
    name: apt-transport-https
    state: latest

- name: pre-install | Add PlasticSCM common packages repository
  apt_repository:
    repo: "deb https://www.plasticscm.com/plasticrepo/plasticscm-common/{{ distro_id }}/ ./"
    state: present

- name: pre-install | Add PlasticSCM-latest repository
  apt_repository:
    repo: "deb https://www.plasticscm.com/plasticrepo/plasticscm-latest/{{ distro_id }}/ ./"
    state: present

- name: pre-install | Add PlasticSCM common repo key
  apt_key:
    url: "https://www.plasticscm.com/plasticrepo/plasticscm-common/{{ distro_id }}/Release.key"
    state: present

- name: pre-install | Add PlasticSCM-latest repo key
  apt_key:
    url: "https://www.plasticscm.com/plasticrepo/plasticscm-latest/{{ distro_id }}/Release.key"
    state: present
